### ISSUE TITLE
Converter fails with error and empties all CSS files

### ISSUE THREAD

**Issue by pepelsbey** [fpetrakov/convert-to-oklch#4]
I tried to run the conversion on my project just to see how it works:

```
npx convert-to-oklch ./src/**/*.css
```

There are two problems:

1. It failed to convert colors (not a big deal)
2. It emptied the files (that’s dangerous)

Here’s [the source code](https://github.com/pepelsbey/pepelsbey.dev) of the project I tried to covert to oklch.

I think the tool should fail just a little bit less destructive :) There might be a case when the code is not in source control.

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/105274/203857433-8e1131b5-c92e-4dbb-8413-d1aa334ebe63.png">

- node 16.17.1
- npm 8.15.0

<details>
<summary>The full log</summary>

```
npx convert-to-oklch ./src/**/*.css
Need to install the following packages:
  convert-to-oklch@1.1.1
Ok to proceed? (y) 
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

TypeError: undefined not allowed for Hue in hsl()
    at /Users/pepelsbey/Documents/Sites/pepelsbey.dev/src/styles/blocks/about-section/dark.css:4:5
    at /Users/pepelsbey/.npm/_npx/507f2505b7b65eb1/node_modules/colorjs.io/dist/color.cjs:851:15
    at Array.forEach (<anonymous>)
    at parse (/Users/pepelsbey/.npm/_npx/507f2505b7b65eb1/node_modules/colorjs.io/dist/color.cjs:839:36)
    at getColor (/Users/pepelsbey/.npm/_npx/507f2505b7b65eb1/node_modules/colorjs.io/dist/color.cjs:918:11)
    at new Color (/Users/pepelsbey/.npm/_npx/507f2505b7b65eb1/node_modules/colorjs.io/dist/color.cjs:3976:12)
    at Declaration (/Users/pepelsbey/.npm/_npx/507f2505b7b65eb1/node_modules/convert-to-oklch/src/plugin.js:10:23)
    at LazyResult.visitSync (/Users/pepelsbey/.npm/_npx/507f2505b7b65eb1/node_modules/postcss/lib/lazy-result.js:308:19)
    at LazyResult.walkSync (/Users/pepelsbey/.npm/_npx/507f2505b7b65eb1/node_modules/postcss/lib/lazy-result.js:297:20)
    at /Users/pepelsbey/.npm/_npx/507f2505b7b65eb1/node_modules/postcss/lib/lazy-result.js:291:39
    at Rule.each (/Users/pepelsbey/.npm/_npx/507f2505b7b65eb1/node_modules/postcss/lib/container.js:41:16) {
  postcssNode: <ref *1> Declaration {
    raws: { before: '\n    ', between: ': ' },
    type: 'decl',
    parent: <ref *3> Rule {
      raws: { before: '\n\n', between: ' ', semicolon: true, after: '\n' },
      type: 'rule',
      nodes: [ [Circular *1] ],
      parent: <ref *2> Root {
        raws: { semicolon: false, after: '\n' },
        type: 'root',
        nodes: [
          Comment {
            raws: [Object],
            type: 'comment',
            parent: [Circular *2],
            source: [Object],
            text: 'About Section',
            [Symbol(isClean)]: true,
            [Symbol(my)]: true
          },
          [Circular *3]
        ],
        source: {
          input: Input {
            css: '/* About Section */\n' +
              '\n' +
              '.about-section {\n' +
              '    --about-section-scribble-fill: hsl(var(--color-manatee) / 0.2);\n' +
              '}\n',
            hasBOM: false,
            file: '/Users/pepelsbey/Documents/Sites/pepelsbey.dev/src/styles/blocks/about-section/dark.css',
            [Symbol(fromOffsetCache)]: [Array]
          },
          start: { offset: 0, line: 1, column: 1 }
        },
        lastEach: 1,
        indexes: { '1': 1 },
        [Symbol(isClean)]: true,
        [Symbol(my)]: true
      },
      source: {
        start: { offset: 21, line: 3, column: 1 },
        input: Input {
          css: '/* About Section */\n' +
            '\n' +
            '.about-section {\n' +
            '    --about-section-scribble-fill: hsl(var(--color-manatee) / 0.2);\n' +
            '}\n',
          hasBOM: false,
          file: '/Users/pepelsbey/Documents/Sites/pepelsbey.dev/src/styles/blocks/about-section/dark.css',
          [Symbol(fromOffsetCache)]: [ 0, 20, 21, 38, 106, 108 ]
        },
        end: { offset: 106, line: 5, column: 1 }
      },
      selector: '.about-section',
      lastEach: 1,
      indexes: { '1': 0 },
      [Symbol(isClean)]: true,
      [Symbol(my)]: true
    },
    source: {
      start: { offset: 42, line: 4, column: 5 },
      input: Input {
        css: '/* About Section */\n' +
          '\n' +
          '.about-section {\n' +
          '    --about-section-scribble-fill: hsl(var(--color-manatee) / 0.2);\n' +
          '}\n',
        hasBOM: false,
        file: '/Users/pepelsbey/Documents/Sites/pepelsbey.dev/src/styles/blocks/about-section/dark.css',
        [Symbol(fromOffsetCache)]: [ 0, 20, 21, 38, 106, 108 ]
      },
      end: { offset: 104, line: 4, column: 67 }
    },
    prop: '--about-section-scribble-fill',
    value: 'hsl(var(--color-manatee) / 0.2)',
    proxyCache: [Circular *1],
    [Symbol(isClean)]: true,
    [Symbol(my)]: true
  }
}
```

</details>

**Comment by fpetrakov** [comment]
Thanks for the PR and such a detailed description. I'm sorry this bug has caused you trouble, I'll try to fix it asap.

**Comment by pepelsbey** [comment]
No worries, it didn't cause me any troubles :) Thanks for the quick fix! I'll give another try.
